apiVersion: v1
kind: Service
metadata:
  name: web-np
  namespace: platform
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: api-np
  namespace: platform
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: nango-np
  namespace: platform
spec:
  type: NodePort
  selector:
    app: nango-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: token-proxy-np
  namespace: platform
spec:
  type: NodePort
  selector:
    app: token-proxy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30800
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-np
  namespace: platform
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
